//! Generated by webidl2zig (model style). Do not edit.

pub const WithEmpty = enum {
    empty,
    value,
};

/// Attributes: bigNum
pub const WithBigint = struct {};

/// Operations: doThing
pub const WithConstructor = struct {};

pub const WithGetter = struct {};

/// Operations: takeNullable
pub const WithNullable = struct {};

/// Operations: doAsync
pub const WithPromise = struct {};

/// Attributes: staticVal
/// Operations: staticOp
pub const WithStatic = struct {};

/// Attributes: type
pub const WithType = struct {};

/// Operations: takeVariadic
pub const WithVariadic = struct {};

/// Operations: sqrt
pub const MathNS = struct {};
