//! Generated by webidl2zig (model style). Do not edit.

pub const ReadyState = enum {
    closed,
    connecting,
    open,
};

pub const RequestInit = struct {
    method: []const u8,
    timeout: i32 = 5000,
};

/// Attributes: url
/// Operations: addEventListener
pub const EventTarget = struct {
    pub const CONNECTING: u16 = 0;
};
