//! Generated by webidl2zig (client style). Do not edit.

const webidl = @import("webidl");

pub const WithEmpty = enum {
    empty,
    value,
};

pub const WithBigint = struct {
    handle: webidl.rt.Handle,
    pub fn get_bigNum(self: WithBigint) i128 {
        const _h = webidl.rt.getAttr(self.handle, "bigNum");
        return @as(i128, webidl.rt.toI64(_h));
    }
    pub fn set_bigNum(self: WithBigint, value: i128) void {
        webidl.rt.setAttr(self.handle, "bigNum", webidl.rt.fromI64(@intCast(value)));
    }
    pub fn ref(self: WithBigint) void {
        webidl.rt.retain(self.handle);
    }
    pub fn unref(self: WithBigint) void {
        webidl.rt.release(self.handle);
    }
};

pub const WithConstructor = struct {
    handle: webidl.rt.Handle,
    pub fn doThing(self: WithConstructor) void {
        _ = webidl.rt.callMethod(self.handle, "doThing", &[_]webidl.rt.Handle{});
    }
    pub fn init(x: i32, y: i32) WithConstructor {
        return .{ .handle = webidl.rt.construct("WithConstructor", &[_]webidl.rt.Handle{ webidl.rt.fromI32(x), webidl.rt.fromI32(y) }) };
    }
    pub fn ref(self: WithConstructor) void {
        webidl.rt.retain(self.handle);
    }
    pub fn unref(self: WithConstructor) void {
        webidl.rt.release(self.handle);
    }
};

pub const WithGetter = struct {
    handle: webidl.rt.Handle,
    pub fn indexedGetter(self: WithGetter, index: u32) []const u8 {
        const _h = webidl.rt.callMethod(self.handle, "indexedGetter", &[_]webidl.rt.Handle{webidl.rt.fromU32(index)});
        return webidl.rt.toStr(_h);
    }
    pub fn ref(self: WithGetter) void {
        webidl.rt.retain(self.handle);
    }
    pub fn unref(self: WithGetter) void {
        webidl.rt.release(self.handle);
    }
};

pub const WithNullable = struct {
    handle: webidl.rt.Handle,
    pub fn takeNullable(self: WithNullable, x: ?i32) void {
        _ = webidl.rt.callMethod(self.handle, "takeNullable", &[_]webidl.rt.Handle{if (x) |__v| webidl.rt.fromI32(__v) else webidl.rt.nullHandle()});
    }
    pub fn ref(self: WithNullable) void {
        webidl.rt.retain(self.handle);
    }
    pub fn unref(self: WithNullable) void {
        webidl.rt.release(self.handle);
    }
};

pub const WithPromise = struct {
    handle: webidl.rt.Handle,
    pub fn doAsync(self: WithPromise) i32 {
        const _h = webidl.rt.callMethod(self.handle, "doAsync", &[_]webidl.rt.Handle{});
        return webidl.rt.toI32(_h);
    }
    pub fn ref(self: WithPromise) void {
        webidl.rt.retain(self.handle);
    }
    pub fn unref(self: WithPromise) void {
        webidl.rt.release(self.handle);
    }
};

pub const WithStatic = struct {
    handle: webidl.rt.Handle,
    pub fn get_staticVal() i32 {
        const _h = webidl.rt.getStaticAttr("WithStatic", "staticVal");
        return webidl.rt.toI32(_h);
    }
    pub fn staticOp(x: i32) void {
        _ = webidl.rt.callStaticMethod("WithStatic", "staticOp", &[_]webidl.rt.Handle{webidl.rt.fromI32(x)});
    }
    pub fn ref(self: WithStatic) void {
        webidl.rt.retain(self.handle);
    }
    pub fn unref(self: WithStatic) void {
        webidl.rt.release(self.handle);
    }
};

pub const WithType = struct {
    handle: webidl.rt.Handle,
    pub fn get_type(self: WithType) []const u8 {
        const _h = webidl.rt.getAttr(self.handle, "type");
        return webidl.rt.toStr(_h);
    }
    pub fn set_type(self: WithType, value: []const u8) void {
        webidl.rt.setAttr(self.handle, "type", webidl.rt.fromStr(value));
    }
    pub fn ref(self: WithType) void {
        webidl.rt.retain(self.handle);
    }
    pub fn unref(self: WithType) void {
        webidl.rt.release(self.handle);
    }
};

pub const WithVariadic = struct {
    handle: webidl.rt.Handle,
    pub fn takeVariadic(self: WithVariadic, xs: []const i32) void {
        // variadic arg 'xs': custom JS marshaling needed
        _ = xs;
        _ = webidl.rt.callMethod(self.handle, "takeVariadic", &[_]webidl.rt.Handle{});
    }
    pub fn ref(self: WithVariadic) void {
        webidl.rt.retain(self.handle);
    }
    pub fn unref(self: WithVariadic) void {
        webidl.rt.release(self.handle);
    }
};

pub const MathNS = struct {
    pub fn sqrt(x: f64) f64 {
        const _h = webidl.rt.callStaticMethod("MathNS", "sqrt", &[_]webidl.rt.Handle{webidl.rt.fromF64(x)});
        return webidl.rt.toF64(_h);
    }
};
