//! Generated by webidl2zig (client style). Do not edit.

const webidl = @import("webidl");

pub const ReadyState = enum {
    closed,
    connecting,
    open,
};

pub const RequestInit = struct {
    method: []const u8,
    timeout: i32 = 5000,
};

pub const EventTarget = struct {
    handle: webidl.rt.Handle,
    pub const CONNECTING: u16 = 0;
    pub fn get_url(self: EventTarget) []const u8 {
        const _h = webidl.rt.getAttr(self.handle, "url");
        return webidl.rt.toStr(_h);
    }
    pub fn addEventListener(self: EventTarget, @"type": []const u8) void {
        _ = webidl.rt.callMethod(self.handle, "addEventListener", &[_]webidl.rt.Handle{webidl.rt.fromStr(@"type")});
    }
    pub fn ref(self: EventTarget) void {
        webidl.rt.retain(self.handle);
    }
    pub fn unref(self: EventTarget) void {
        webidl.rt.release(self.handle);
    }
};
