//! Generated by webidl2zig (host style). Do not edit.

const std = @import("std");

pub const WithEmpty = enum {
    empty,
    value,
};

pub const WithBigint = struct {
    vtable: *const VTable,
    refs: usize = 1,

    pub const VTable = struct {
        get_bigNum: *const fn (self: *WithBigint) i128,
        set_bigNum: *const fn (self: *WithBigint, value: i128) void,
        destroy: *const fn (self: *WithBigint) void,
    };

    pub fn get_bigNum(self: *WithBigint) i128 {
        return self.vtable.get_bigNum(self);
    }

    pub fn set_bigNum(self: *WithBigint, value: i128) void {
        self.vtable.set_bigNum(self, value);
    }

    pub fn ref(self: *WithBigint) void {
        _ = @atomicRmw(usize, &self.refs, .Add, 1, .monotonic);
    }

    pub fn unref(self: *WithBigint) void {
        if (@atomicRmw(usize, &self.refs, .Sub, 1, .acq_rel) == 1) self.vtable.destroy(self);
    }
};

pub const WithConstructor = struct {
    vtable: *const VTable,
    refs: usize = 1,

    pub const VTable = struct {
        doThing: *const fn (self: *WithConstructor) void,
        construct: *const fn (gpa: std.mem.Allocator, io: std.Io, x: i32, y: i32) *WithConstructor,
        destroy: *const fn (self: *WithConstructor) void,
    };

    pub fn doThing(self: *WithConstructor) void {
        return self.vtable.doThing(self);
    }

    pub fn construct(gpa: std.mem.Allocator, io: std.Io, vtable: *const WithConstructor.VTable, x: i32, y: i32) *WithConstructor {
        return vtable.construct(gpa, io, x, y);
    }

    pub fn ref(self: *WithConstructor) void {
        _ = @atomicRmw(usize, &self.refs, .Add, 1, .monotonic);
    }

    pub fn unref(self: *WithConstructor) void {
        if (@atomicRmw(usize, &self.refs, .Sub, 1, .acq_rel) == 1) self.vtable.destroy(self);
    }
};

pub const WithGetter = struct {
    vtable: *const VTable,
    refs: usize = 1,

    pub const VTable = struct {
        indexedGetter: *const fn (self: *WithGetter, index: u32) []const u8,
        destroy: *const fn (self: *WithGetter) void,
    };

    pub fn indexedGetter(self: *WithGetter, index: u32) []const u8 {
        return self.vtable.indexedGetter(self, index);
    }

    pub fn ref(self: *WithGetter) void {
        _ = @atomicRmw(usize, &self.refs, .Add, 1, .monotonic);
    }

    pub fn unref(self: *WithGetter) void {
        if (@atomicRmw(usize, &self.refs, .Sub, 1, .acq_rel) == 1) self.vtable.destroy(self);
    }
};

pub const WithNullable = struct {
    vtable: *const VTable,
    refs: usize = 1,

    pub const VTable = struct {
        takeNullable: *const fn (self: *WithNullable, x: ?i32) void,
        destroy: *const fn (self: *WithNullable) void,
    };

    pub fn takeNullable(self: *WithNullable, x: ?i32) void {
        return self.vtable.takeNullable(self, x);
    }

    pub fn ref(self: *WithNullable) void {
        _ = @atomicRmw(usize, &self.refs, .Add, 1, .monotonic);
    }

    pub fn unref(self: *WithNullable) void {
        if (@atomicRmw(usize, &self.refs, .Sub, 1, .acq_rel) == 1) self.vtable.destroy(self);
    }
};

pub const WithPromise = struct {
    vtable: *const VTable,
    refs: usize = 1,

    pub const VTable = struct {
        doAsync: *const fn (self: *WithPromise) i32,
        destroy: *const fn (self: *WithPromise) void,
    };

    pub fn doAsync(self: *WithPromise) i32 {
        return self.vtable.doAsync(self);
    }

    pub fn ref(self: *WithPromise) void {
        _ = @atomicRmw(usize, &self.refs, .Add, 1, .monotonic);
    }

    pub fn unref(self: *WithPromise) void {
        if (@atomicRmw(usize, &self.refs, .Sub, 1, .acq_rel) == 1) self.vtable.destroy(self);
    }
};

pub const WithStatic = struct {
    pub fn get_staticVal() i32 {
        unreachable;
    }

    pub fn staticOp(x: i32) void {
        _ = x;
        unreachable;
    }
};

pub const WithType = struct {
    vtable: *const VTable,
    refs: usize = 1,

    pub const VTable = struct {
        get_type: *const fn (self: *WithType) []const u8,
        set_type: *const fn (self: *WithType, value: []const u8) void,
        destroy: *const fn (self: *WithType) void,
    };

    pub fn get_type(self: *WithType) []const u8 {
        return self.vtable.get_type(self);
    }

    pub fn set_type(self: *WithType, value: []const u8) void {
        self.vtable.set_type(self, value);
    }

    pub fn ref(self: *WithType) void {
        _ = @atomicRmw(usize, &self.refs, .Add, 1, .monotonic);
    }

    pub fn unref(self: *WithType) void {
        if (@atomicRmw(usize, &self.refs, .Sub, 1, .acq_rel) == 1) self.vtable.destroy(self);
    }
};

pub const WithVariadic = struct {
    vtable: *const VTable,
    refs: usize = 1,

    pub const VTable = struct {
        takeVariadic: *const fn (self: *WithVariadic, xs: []const i32) void,
        destroy: *const fn (self: *WithVariadic) void,
    };

    pub fn takeVariadic(self: *WithVariadic, xs: []const i32) void {
        return self.vtable.takeVariadic(self, xs);
    }

    pub fn ref(self: *WithVariadic) void {
        _ = @atomicRmw(usize, &self.refs, .Add, 1, .monotonic);
    }

    pub fn unref(self: *WithVariadic) void {
        if (@atomicRmw(usize, &self.refs, .Sub, 1, .acq_rel) == 1) self.vtable.destroy(self);
    }
};

pub const MathNS = struct {
    pub fn sqrt(x: f64) f64 {
        _ = x;
        unreachable;
    }
};
