//! Generated by webidl2zig (host style). Do not edit.

pub const ReadyState = enum {
    closed,
    connecting,
    open,
};

pub const RequestInit = struct {
    method: []const u8,
    timeout: i32 = 5000,
};

pub const EventTarget = struct {
    pub const CONNECTING: u16 = 0;

    vtable: *const VTable,
    refs: usize = 1,

    pub const VTable = struct {
        get_url: *const fn (self: *EventTarget) []const u8,
        addEventListener: *const fn (self: *EventTarget, @"type": []const u8) void,
        destroy: *const fn (self: *EventTarget) void,
    };

    pub fn get_url(self: *EventTarget) []const u8 {
        return self.vtable.get_url(self);
    }

    pub fn addEventListener(self: *EventTarget, @"type": []const u8) void {
        return self.vtable.addEventListener(self, @"type");
    }

    pub fn ref(self: *EventTarget) void {
        _ = @atomicRmw(usize, &self.refs, .Add, 1, .monotonic);
    }

    pub fn unref(self: *EventTarget) void {
        if (@atomicRmw(usize, &self.refs, .Sub, 1, .acq_rel) == 1) self.vtable.destroy(self);
    }
};
