//! Shared helpers for all webidl2zig style emitters.

const std = @import("std");
const model = @import("../model.zig");
const naming = @import("../naming.zig");
const parser_mod = @import("../parser.zig");
const resolve_mod = @import("../resolve.zig");

pub const Error = error{ WriteFailed, OutOfMemory, Unimplemented };

pub const Style = enum { model, host, client };

/// Standard generated-file banner. Ends with two newlines (one blank line).
pub fn header(w: *std.Io.Writer, style: Style) Error!void {
    try w.print("//! Generated by webidl2zig ({s} style). Do not edit.\n\n", .{@tagName(style)});
}

/// Map a model.Type to Zig syntax for the model style.
/// Writes directly to `w`. `gpa` is used only for `naming.zigIdent` on named types.
pub fn zigType(w: *std.Io.Writer, gpa: std.mem.Allocator, t: model.Type) Error!void {
    switch (t) {
        .boolean => try w.writeAll("bool"),
        .byte => try w.writeAll("i8"),
        .octet => try w.writeAll("u8"),
        .short => try w.writeAll("i16"),
        .unsigned_short => try w.writeAll("u16"),
        .long => try w.writeAll("i32"),
        .unsigned_long => try w.writeAll("u32"),
        .long_long => try w.writeAll("i64"),
        .unsigned_long_long => try w.writeAll("u64"),
        .float, .unrestricted_float => try w.writeAll("f32"),
        .double, .unrestricted_double => try w.writeAll("f64"),
        .bigint => try w.writeAll("i128"),
        .dom_string, .byte_string, .usv_string => try w.writeAll("[]const u8"),
        .object, .any, .symbol => try w.writeAll("*anyopaque"),
        .undefined => try w.writeAll("void"),
        .sequence => |inner| {
            try w.writeAll("[]const ");
            try zigType(w, gpa, inner.*);
        },
        .frozen_array => |inner| {
            try w.writeAll("[]const ");
            try zigType(w, gpa, inner.*);
        },
        .observable_array => |inner| {
            try w.writeAll("[]const ");
            try zigType(w, gpa, inner.*);
        },
        .nullable => |inner| {
            try w.writeByte('?');
            try zigType(w, gpa, inner.*);
        },
        .promise => |inner| try zigType(w, gpa, inner.*), // async not modeled, emit T
        .record => |r| {
            try w.writeAll("[]const struct{ key: ");
            try zigType(w, gpa, r.key.*);
            try w.writeAll(", value: ");
            try zigType(w, gpa, r.value.*);
            try w.writeByte('}');
        },
        .union_of => try w.writeAll("*anyopaque"), // TODO: union types not yet modeled
        .buffer => try w.writeAll("[]const u8"), // buffer placeholder
        .named => |name| {
            const ident = naming.zigIdent(gpa, name) catch return error.OutOfMemory;
            defer gpa.free(ident);
            try w.writeAll(ident);
        },
    }
}

/// Emit a ValueLiteral as a Zig literal expression.
/// Note: inf/nan constants require the caller's generated file to import std.
pub fn zigConstValue(w: *std.Io.Writer, v: model.ValueLiteral) Error!void {
    switch (v) {
        .boolean => |b| try w.writeAll(if (b) "true" else "false"),
        .integer => |i| try w.print("{d}", .{i}),
        .decimal => |d| try w.print("{d}", .{d}),
        .string => |s| {
            try w.writeByte('"');
            for (s) |c| {
                switch (c) {
                    '"' => try w.writeAll("\\\""),
                    '\\' => try w.writeAll("\\\\"),
                    '\n' => try w.writeAll("\\n"),
                    '\r' => try w.writeAll("\\r"),
                    '\t' => try w.writeAll("\\t"),
                    else => try w.writeByte(c),
                }
            }
            try w.writeByte('"');
        },
        .null_value => try w.writeAll("null"),
        .undefined_value => try w.writeAll("undefined"),
        .empty_sequence => try w.writeAll("&.{}"),
        .empty_dict => try w.writeAll(".{}"),
        .positive_infinity => try w.writeAll("std.math.inf(f64)"),
        .negative_infinity => try w.writeAll("-std.math.inf(f64)"),
        .nan => try w.writeAll("std.math.nan(f64)"),
    }
}

/// Return the generated Zig identifier for a special WebIDL operation.
pub fn specialOpName(special: model.SpecialOperation) []const u8 {
    return switch (special) {
        .getter => "indexedGetter",
        .setter => "indexedSetter",
        .deleter => "deleter",
        .legacy_caller => "legacyCaller",
    };
}

/// Emit the Zig type for an operation argument.
/// Variadic args (WebIDL `...T`) become `[]const T`, others become `T`.
pub fn zigArgType(w: *std.Io.Writer, gpa: std.mem.Allocator, arg: model.Argument) Error!void {
    if (arg.variadic) {
        try w.writeAll("[]const ");
    }
    try zigType(w, gpa, arg.type);
}

/// Sort a slice of items that each have a `name: []const u8` field, in place, ascending.
pub fn sortByName(comptime T: type, items: []T) void {
    const Ctx = struct {
        fn less(_: void, a: T, b: T) bool {
            return std.mem.lessThan(u8, a.name, b.name);
        }
    };
    std.mem.sort(T, items, {}, Ctx.less);
}

/// Return a sorted copy of `slice`. Caller owns the result (free with gpa.free).
pub fn sortedCopy(comptime T: type, gpa: std.mem.Allocator, slice: []const T) Error![]T {
    const copy = gpa.dupe(T, slice) catch return error.OutOfMemory;
    sortByName(T, copy);
    return copy;
}

/// Emit a WebIDL enum as `pub const E = enum { ... };`. Values sorted alphabetically.
pub fn emitEnum(w: *std.Io.Writer, gpa: std.mem.Allocator, en: model.Enum) Error!void {
    const ident = naming.zigIdent(gpa, en.name) catch return error.OutOfMemory;
    defer gpa.free(ident);
    try w.print("pub const {s} = enum {{\n", .{ident});
    const sorted_vals = gpa.dupe([]const u8, en.values) catch return error.OutOfMemory;
    defer gpa.free(sorted_vals);
    std.mem.sort([]const u8, sorted_vals, {}, struct {
        fn less(_: void, a: []const u8, b: []const u8) bool {
            return std.mem.lessThan(u8, a, b);
        }
    }.less);
    for (sorted_vals) |val| {
        const val_ident = naming.zigIdent(gpa, val) catch return error.OutOfMemory;
        defer gpa.free(val_ident);
        try w.print("    {s},\n", .{val_ident});
    }
    try w.writeAll("};\n");
}

/// Emit a WebIDL callback as `pub const Cb = *const fn (...) R;`.
pub fn emitCallback(w: *std.Io.Writer, gpa: std.mem.Allocator, cb: model.Callback) Error!void {
    const ident = naming.zigIdent(gpa, cb.name) catch return error.OutOfMemory;
    defer gpa.free(ident);
    try w.print("pub const {s} = *const fn (", .{ident});
    for (cb.args, 0..) |arg, i| {
        if (i > 0) try w.writeAll(", ");
        const arg_ident = naming.zigIdent(gpa, arg.name) catch return error.OutOfMemory;
        defer gpa.free(arg_ident);
        try w.print("{s}: ", .{arg_ident});
        try zigArgType(w, gpa, arg);
    }
    try w.writeAll(") ");
    try zigType(w, gpa, cb.return_type);
    try w.writeAll(";\n");
}

/// Emit a WebIDL dictionary as `pub const D = struct { ... };`.
pub fn emitDictionary(w: *std.Io.Writer, gpa: std.mem.Allocator, dict: model.Dictionary) Error!void {
    const ident = naming.zigIdent(gpa, dict.name) catch return error.OutOfMemory;
    defer gpa.free(ident);
    if (dict.inherits) |base| {
        try w.print("/// Extends: {s}\n", .{base});
    }
    try w.print("pub const {s} = struct {{\n", .{ident});
    for (dict.members) |m| {
        const mem_ident = naming.zigIdent(gpa, m.name) catch return error.OutOfMemory;
        defer gpa.free(mem_ident);
        try w.print("    {s}: ", .{mem_ident});
        if (m.required) {
            try zigType(w, gpa, m.type);
        } else if (m.default) |d| {
            try zigType(w, gpa, m.type);
            try w.writeAll(" = ");
            try zigConstValue(w, d);
        } else {
            try w.writeByte('?');
            try zigType(w, gpa, m.type);
            try w.writeAll(" = null");
        }
        try w.writeAll(",\n");
    }
    try w.writeAll("};\n");
}

/// Parse WebIDL source, resolve it, then emit in `style` to `w`.
/// Parse/resolve diagnostics are gathered but do not abort emission.
/// Emit a style into a buffer, then reformat it so output matches `zig fmt`.
/// Falls back to the raw buffer when the emitted source will not parse.
fn emitStyle(gpa: std.mem.Allocator, style: Style, w: *std.Io.Writer, defs: model.Definitions) !void {
    var buf: std.Io.Writer.Allocating = .init(gpa);
    defer buf.deinit();
    switch (style) {
        .model => try @import("model_only.zig").emit(&buf.writer, gpa, defs),
        .host => try @import("host.zig").emit(&buf.writer, gpa, defs),
        .client => try @import("client.zig").emit(&buf.writer, gpa, defs),
    }
    const raw = buf.writer.buffered();

    const src0 = try gpa.dupeZ(u8, raw);
    defer gpa.free(src0);
    var ast = try std.zig.Ast.parse(gpa, src0, .zig);
    defer ast.deinit(gpa);
    if (ast.errors.len > 0) {
        try w.writeAll(raw);
        return;
    }
    const formatted = try ast.renderAlloc(gpa);
    defer gpa.free(formatted);
    try w.writeAll(formatted);
}

pub fn generate(gpa: std.mem.Allocator, src: []const u8, style: Style, w: *std.Io.Writer) !void {
    var parsed = try parser_mod.parse_src(gpa, src);
    defer parsed.deinit();
    defer parsed.diagnostics.deinit(gpa);

    var resolved = try resolve_mod.resolve(gpa, &parsed);
    defer resolved.deinit();
    defer resolved.diagnostics.deinit(gpa);

    try emitStyle(gpa, style, w, resolved.defs);
}

/// Like generate but emits the JSON IR instead of a Zig style.
pub fn generateIr(gpa: std.mem.Allocator, src: []const u8, w: *std.Io.Writer) !void {
    var parsed = try parser_mod.parse_src(gpa, src);
    defer parsed.deinit();
    defer parsed.diagnostics.deinit(gpa);

    var resolved = try resolve_mod.resolve(gpa, &parsed);
    defer resolved.deinit();
    defer resolved.diagnostics.deinit(gpa);

    try @import("json_ir.zig").emit(w, gpa, resolved.defs);
}

/// Like generateChecked but emits the JSON IR. Writes diagnostics to err_w and
/// returns error.HasDiagnostics when any .err severity diagnostic is found.
pub fn generateIrChecked(
    gpa: std.mem.Allocator,
    src: []const u8,
    w: *std.Io.Writer,
    err_w: *std.Io.Writer,
    mozilla: bool,
) !void {
    var parsed = try parser_mod.parse_srcOpts(gpa, src, .{ .mozilla = mozilla });
    defer parsed.deinit();
    defer parsed.diagnostics.deinit(gpa);

    var resolved = try resolve_mod.resolve(gpa, &parsed);
    defer resolved.deinit();
    defer resolved.diagnostics.deinit(gpa);

    var has_errors = false;
    for (parsed.diagnostics.list.items) |d| {
        try d.format(err_w);
        try err_w.writeByte('\n');
        if (d.severity == .err) has_errors = true;
    }
    for (resolved.diagnostics.list.items) |d| {
        try d.format(err_w);
        try err_w.writeByte('\n');
        if (d.severity == .err) has_errors = true;
    }

    if (has_errors) return error.HasDiagnostics;

    try @import("json_ir.zig").emit(w, gpa, resolved.defs);
}

/// Like generate, but writes all diagnostics to err_w and returns
/// error.HasDiagnostics when any .err severity diagnostic was found,
/// without emitting to w in that case.
pub fn generateChecked(
    gpa: std.mem.Allocator,
    src: []const u8,
    style: Style,
    w: *std.Io.Writer,
    err_w: *std.Io.Writer,
    mozilla: bool,
) !void {
    var parsed = try parser_mod.parse_srcOpts(gpa, src, .{ .mozilla = mozilla });
    defer parsed.deinit();
    defer parsed.diagnostics.deinit(gpa);

    var resolved = try resolve_mod.resolve(gpa, &parsed);
    defer resolved.deinit();
    defer resolved.diagnostics.deinit(gpa);

    var has_errors = false;
    for (parsed.diagnostics.list.items) |d| {
        try d.format(err_w);
        try err_w.writeByte('\n');
        if (d.severity == .err) has_errors = true;
    }
    for (resolved.diagnostics.list.items) |d| {
        try d.format(err_w);
        try err_w.writeByte('\n');
        if (d.severity == .err) has_errors = true;
    }

    if (has_errors) return error.HasDiagnostics;

    try emitStyle(gpa, style, w, resolved.defs);
}

// Tests

const testing = std.testing;

test "header emits banner" {
    var aw: std.Io.Writer.Allocating = .init(testing.allocator);
    defer aw.deinit();
    try header(&aw.writer, .model);
    try testing.expectEqualStrings(
        "//! Generated by webidl2zig (model style). Do not edit.\n\n",
        aw.writer.buffered(),
    );
}

test "zigType: boolean" {
    var aw: std.Io.Writer.Allocating = .init(testing.allocator);
    defer aw.deinit();
    try zigType(&aw.writer, testing.allocator, .boolean);
    try testing.expectEqualStrings("bool", aw.writer.buffered());
}

test "zigType: unsigned_short" {
    var aw: std.Io.Writer.Allocating = .init(testing.allocator);
    defer aw.deinit();
    try zigType(&aw.writer, testing.allocator, .unsigned_short);
    try testing.expectEqualStrings("u16", aw.writer.buffered());
}

test "zigType: long" {
    var aw: std.Io.Writer.Allocating = .init(testing.allocator);
    defer aw.deinit();
    try zigType(&aw.writer, testing.allocator, .long);
    try testing.expectEqualStrings("i32", aw.writer.buffered());
}

test "zigType: dom_string" {
    var aw: std.Io.Writer.Allocating = .init(testing.allocator);
    defer aw.deinit();
    try zigType(&aw.writer, testing.allocator, .dom_string);
    try testing.expectEqualStrings("[]const u8", aw.writer.buffered());
}

test "zigType: undefined" {
    var aw: std.Io.Writer.Allocating = .init(testing.allocator);
    defer aw.deinit();
    try zigType(&aw.writer, testing.allocator, .undefined);
    try testing.expectEqualStrings("void", aw.writer.buffered());
}

test "zigType: nullable sequence of long" {
    var inner: model.Type = .long;
    var seq: model.Type = .{ .sequence = &inner };
    var aw: std.Io.Writer.Allocating = .init(testing.allocator);
    defer aw.deinit();
    try zigType(&aw.writer, testing.allocator, .{ .nullable = &seq });
    try testing.expectEqualStrings("?[]const i32", aw.writer.buffered());
}

test "zigType: named type" {
    var aw: std.Io.Writer.Allocating = .init(testing.allocator);
    defer aw.deinit();
    try zigType(&aw.writer, testing.allocator, .{ .named = "EventTarget" });
    try testing.expectEqualStrings("EventTarget", aw.writer.buffered());
}

test "zigConstValue: integer zero" {
    var aw: std.Io.Writer.Allocating = .init(testing.allocator);
    defer aw.deinit();
    try zigConstValue(&aw.writer, .{ .integer = 0 });
    try testing.expectEqualStrings("0", aw.writer.buffered());
}

test "zigConstValue: boolean true" {
    var aw: std.Io.Writer.Allocating = .init(testing.allocator);
    defer aw.deinit();
    try zigConstValue(&aw.writer, .{ .boolean = true });
    try testing.expectEqualStrings("true", aw.writer.buffered());
}

test "zigConstValue: string literal" {
    var aw: std.Io.Writer.Allocating = .init(testing.allocator);
    defer aw.deinit();
    try zigConstValue(&aw.writer, .{ .string = "hello" });
    try testing.expectEqualStrings("\"hello\"", aw.writer.buffered());
}

test "zigConstValue: string with special chars escaped" {
    var aw: std.Io.Writer.Allocating = .init(testing.allocator);
    defer aw.deinit();
    try zigConstValue(&aw.writer, .{ .string = "say \"hi\"\nline2" });
    try testing.expectEqualStrings("\"say \\\"hi\\\"\\nline2\"", aw.writer.buffered());
}

test "sortByName: sorts Enum slice" {
    var items = [_]model.Enum{
        .{ .name = "Zeta", .values = &.{} },
        .{ .name = "Alpha", .values = &.{} },
        .{ .name = "Mu", .values = &.{} },
    };
    sortByName(model.Enum, &items);
    try testing.expectEqualStrings("Alpha", items[0].name);
    try testing.expectEqualStrings("Mu", items[1].name);
    try testing.expectEqualStrings("Zeta", items[2].name);
}

test "generate: model smoke" {
    const src = "enum E { \"a\", \"b\" };";
    var aw: std.Io.Writer.Allocating = .init(testing.allocator);
    defer aw.deinit();
    try generate(testing.allocator, src, .model, &aw.writer);
    const out = aw.writer.buffered();
    try testing.expect(std.mem.indexOf(u8, out, "pub const E = enum {") != null);
}

test "zigArgType: variadic emits slice prefix" {
    const arg = model.Argument{
        .name = "xs",
        .type = .long,
        .optional = false,
        .variadic = true,
        .default = null,
    };
    var aw: std.Io.Writer.Allocating = .init(testing.allocator);
    defer aw.deinit();
    try zigArgType(&aw.writer, testing.allocator, arg);
    try testing.expectEqualStrings("[]const i32", aw.writer.buffered());
}

test "zigArgType: non-variadic passes through to zigType" {
    const arg = model.Argument{
        .name = "x",
        .type = .long,
        .optional = false,
        .variadic = false,
        .default = null,
    };
    var aw: std.Io.Writer.Allocating = .init(testing.allocator);
    defer aw.deinit();
    try zigArgType(&aw.writer, testing.allocator, arg);
    try testing.expectEqualStrings("i32", aw.writer.buffered());
}

test "generateChecked: malformed input returns HasDiagnostics and writes to err_w" {
    const src = "interface Bad { NoSuchType doThing(); };";
    var out: std.Io.Writer.Allocating = .init(testing.allocator);
    defer out.deinit();
    var err: std.Io.Writer.Allocating = .init(testing.allocator);
    defer err.deinit();
    const result = generateChecked(testing.allocator, src, .model, &out.writer, &err.writer, false);
    try testing.expectError(error.HasDiagnostics, result);
    try testing.expect(err.writer.buffered().len > 0);
    try testing.expectEqualStrings("", out.writer.buffered());
}

test "generateChecked: valid input emits and produces empty err_w" {
    const src = "enum E { \"a\", \"b\" };";
    var out: std.Io.Writer.Allocating = .init(testing.allocator);
    defer out.deinit();
    var err: std.Io.Writer.Allocating = .init(testing.allocator);
    defer err.deinit();
    try generateChecked(testing.allocator, src, .model, &out.writer, &err.writer, false);
    try testing.expect(out.writer.buffered().len > 0);
    try testing.expectEqualStrings("", err.writer.buffered());
}
