//! Generated by webidl2zig (client style). Do not edit.

const webidl = @import("webidl");

pub const Element = struct {
    handle: webidl.rt.Handle,
    pub fn get_textContent(self: Element) []const u8 {
        const _h = webidl.rt.getAttr(self.handle, "textContent");
        return webidl.rt.toStr(_h);
    }
    pub fn set_textContent(self: Element, value: []const u8) void {
        webidl.rt.setAttr(self.handle, "textContent", webidl.rt.fromStr(value));
    }
    pub fn appendChild(self: Element, child: Element) Element {
        const _h = webidl.rt.callMethod(self.handle, "appendChild", &[_]webidl.rt.Handle{child.handle});
        return Element{ .handle = _h };
    }
    pub fn ref(self: Element) void {
        webidl.rt.retain(self.handle);
    }
    pub fn unref(self: Element) void {
        webidl.rt.release(self.handle);
    }
};
