name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-macos, aarch64-macos]
        optimize: [ReleaseSmall, Debug]
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.16.0
      - name: Build
        run: |
          zig build -Dtarget=${{ matrix.target }} -Doptimize=${{ matrix.optimize }}
      - name: Test
        run: |
          zig build test
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x86_64-windows, aarch64-windows]
        optimize: [ReleaseSmall, Debug]
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.16.0
      - name: Build
        run: |
          zig build -Dtarget=${{ matrix.target }} -Doptimize=${{ matrix.optimize }}
      - name: Test
        run: |
          zig build test
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-linux, aarch64-linux, riscv64-linux]
        optimize: [ReleaseSmall, Debug]
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.16.0
      - name: Build
        run: |
          zig build -Dtarget=${{ matrix.target }} -Doptimize=${{ matrix.optimize }}
      - name: Test
        run: |
          zig build test
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: cd npm && npm install
      - name: Build webidl-runtime
        run: cd npm && npm -w @midstall/webidl-runtime run build
      - name: Build webidl-codegen
        run: cd npm && npm -w @midstall/webidl-codegen run build
      - name: Test webidl-runtime
        run: cd npm && npm -w @midstall/webidl-runtime test
      - name: Test webidl-codegen
        run: cd npm && npm -w @midstall/webidl-codegen test
